### ISSUE TITLE
扫描登录之后cookie文件夹下没有自动生成cookie文件 导致报错

### ISSUE THREAD

**Issue by zhaozg5209** [huanghyw/jd_seckill#118]

**Comment by huanghyw** [comment]
图片查看器背景需要白色

**Comment by zhaozg5209** [comment]
> 图片查看器背景需要白色

不是这个问题 这个问题解决了 成功登录了  代码报错
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    jd_seckill.reserve()
  File "D:\GIT\github\jd_seckill-master\jd_spider_requests.py", line 309, in new_func
    self.login_by_qrcode()
  File "D:\GIT\github\jd_seckill-master\jd_spider_requests.py", line 297, in login_by_qrcode
    self.spider_session.save_cookies_to_local(self.nick_name)
  File "D:\GIT\github\jd_seckill-master\jd_spider_requests.py", line 96, in save_cookies_to_local
    with open(cookies_file, 'wb') as f:
OSError: [Errno 22] Invalid argument: './cookies/JD185*****209.cookies'

**Comment by huanghyw** [comment]
目前不支持昵称里面有特殊字符，先调整下昵称吧，把星号去掉。
这个问题后续会修复。
