### ISSUE TITLE
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by barry-gq** [huanghyw/jd_seckill#151]
oooo oooooooooo.            .oooooo..o                     oooo         o8o  oooo  oooo  
       `888 `888'   `Y8b          d8P'    `Y8                     `888         `"'  `888  `888  
        888  888      888         Y88bo.       .ooooo.   .ooooo.   888  oooo  oooo   888   888  
        888  888      888          `"Y8888o.  d88' `88b d88' `"Y8  888 .8P'   `888   888   888  
        888  888      888 8888888      `"Y88b 888ooo888 888        888888.     888   888   888  
        888  888     d88'         oo     .d8P 888    .o 888   .o8  888 `88b.   888   888   888  
    .o. 88P o888bood8P'           8""88888P'  `Y8bod8P' `Y8bod8P' o888o o888o o888o o888o o888o 
    `Y888P                                                                                                                                                  
                                               
功能列表：                                                                                
 1.预约商品
 2.秒杀抢购商品
    
--- Logging error ---
Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 659, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 279, in _get_conn
    return conn or self._new_conn()
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 946, in _new_conn
    "Can't connect to HTTPS URL because the SSL module is not available."
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='order.jd.com', port=443): Max retries exceeded with url: /center/list.action?rid=1609168801768 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 139, in _validate_cookies
    resp = self.session.get(url=url, params=payload, allow_redirects=False)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='order.jd.com', port=443): Max retries exceeded with url: /center/list.action?rid=1609168801768 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 270, in __init__
    self.qrlogin = QrLogin(self.spider_session)
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 119, in __init__
    self.refresh_login_status()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 126, in refresh_login_status
    self.is_login = self._validate_cookies()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 143, in _validate_cookies
    logger.error("验证cookies是否有效发生异常", e)
Message: '验证cookies是否有效发生异常'
Arguments: (SSLError(MaxRetryError('HTTPSConnectionPool(host=\'order.jd.com\', port=443): Max retries exceeded with url: /center/list.action?rid=1609168801768 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",))',),),)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 659, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 279, in _get_conn
    return conn or self._new_conn()
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 946, in _new_conn
    "Can't connect to HTTPS URL because the SSL module is not available."
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='order.jd.com', port=443): Max retries exceeded with url: /center/list.action?rid=1609168801768 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 139, in _validate_cookies
    resp = self.session.get(url=url, params=payload, allow_redirects=False)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='order.jd.com', port=443): Max retries exceeded with url: /center/list.action?rid=1609168801768 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/Python-3.6.1/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/Python-3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 270, in __init__
    self.qrlogin = QrLogin(self.spider_session)
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 119, in __init__
    self.refresh_login_status()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 126, in refresh_login_status
    self.is_login = self._validate_cookies()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 143, in _validate_cookies
    logger.error("验证cookies是否有效发生异常", e)
Message: '验证cookies是否有效发生异常'
Arguments: (SSLError(MaxRetryError('HTTPSConnectionPool(host=\'order.jd.com\', port=443): Max retries exceeded with url: /center/list.action?rid=1609168801768 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.",))',),),)
Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 659, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 279, in _get_conn
    return conn or self._new_conn()
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 946, in _new_conn
    "Can't connect to HTTPS URL because the SSL module is not available."
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.jd.com', port=443): Max retries exceeded with url: //ajax/queryServerData.html (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "/root/gq/jd_seckill-master/jd_seckill-master/jd_spider_requests.py", line 278, in __init__
    self.timers = Timer()
  File "/root/gq/jd_seckill-master/jd_seckill-master/timer.py", line 18, in __init__
    self.diff_time = self.local_jd_time_diff()
  File "/root/gq/jd_seckill-master/jd_seckill-master/timer.py", line 42, in local_jd_time_diff
    return self.local_time() - self.jd_time()
  File "/root/gq/jd_seckill-master/jd_seckill-master/timer.py", line 26, in jd_time
    ret = requests.get(url).text
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/Python-3.6.1/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='a.jd.com', port=443): Max retries exceeded with url: //ajax/queryServerData.html (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)

**Comment by barry-gq** [comment]
你好，请问这是什么问题

**Comment by barry-gq** [comment]
我python 版本是3.6.1

**Comment by syouko** [comment]
估计是依赖没安装完。
pip install -r re....和pip3 install -r re.... 都安装下

**Comment by barry-gq** [comment]
> 估计是依赖没安装完。
> pip install -r re....和pip3 install -r re.... 都安装下

试过了，查了一下好像是ssl用的不对，我是centos7，把py2升到了3，但可能会导致ssl出问题。。，准备用windows试试了

**Comment by barry-gq** [comment]
> 估计是依赖没安装完。
> pip install -r re....和pip3 install -r re.... 都安装下

话说你是用的windows 还是centos 运行py

**Comment by syouko** [comment]
> > 估计是依赖没安装完。
> > pip install -r re....和pip3 install -r re.... 都安装下
> 
> 话说你是用的windows 还是centos 运行py

我用的 Debian 10

**Comment by teg1c** [comment]
昨天运行就没问题,今天运行就报这个错误

**Comment by barry-gq** [comment]
> 昨天运行就没问题,今天运行就报这个错误

我以为是我环境有问题，我昨天才开始，然后看了一下代码昨天有更新

**Comment by barry-gq** [comment]
> 昨天运行就没问题,今天运行就报这个错误

期间你有升级过代码或者环境吗

**Comment by teg1c** [comment]
> > 昨天运行就没问题,今天运行就报这个错误
> 
> 期间你有升级过代码或者环境吗

没有的

**Comment by barry-gq** [comment]
> > > 昨天运行就没问题,今天运行就报这个错误
> > 
> > 
> > 期间你有升级过代码或者环境吗
> 
> 没有的

那我也不会了，我昨天才开始研究，今天准备试试windows运行

**Comment by barry-gq** [comment]
> > > 估计是依赖没安装完。
> > > pip install -r re....和pip3 install -r re.... 都安装下
> > 
> > 
> > 话说你是用的windows 还是centos 运行py
> 
> 我用的 Debian 10

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: certifi==2020.4.5.1 in /usr/local/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2020.4.5.1)
Requirement already satisfied: chardet==3.0.4 in /usr/local/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna==2.9 in /usr/local/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (2.9)
Requirement already satisfied: lxml==4.5.1 in /usr/local/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (4.5.1)
Requirement already satisfied: requests==2.23.0 in /usr/local/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.23.0)
Requirement already satisfied: urllib3==1.25.9 in /usr/local/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (1.25.9)

这是安装的requirement.txt依赖结果，看起来没问题

**Comment by barry-gq** [comment]
我昨天装的py3.6不行，今天装了3.7版本就好了，大家可以试试
