### ISSUE TITLE
每次抢的时候走到这就报这些错误，但是过了一会再执行就是正常的

### ISSUE THREAD

**Issue by liuguangruge** [huanghyw/jd_seckill#173]
2020-12-29 10:03:07,108 INFO: 生成提交抢购订单所需参数...
2020-12-29 10:03:07,108 INFO: 获取秒杀初始化信息...
^CTraceback (most recent call last):
  File "main.py", line 21, in <module>
    start_tool.submit_seckill_order()
  File "/root/MyPythonProjects/mt_liuyong/jd_mask_spider_requests.py", line 248, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "/root/MyPythonProjects/mt_liuyong/jd_mask_spider_requests.py", line 198, in _get_seckill_order_data
    self.seckill_init_info[self.sku_id] = self._get_seckill_init_info()
  File "/root/MyPythonProjects/mt_liuyong/jd_mask_spider_requests.py", line 184, in _get_seckill_init_info
    resp = self.session.post(url=url, data=data, headers=headers)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname

**Comment by imageslr** [comment]
+1
