### ISSUE TITLE
请问有人登录失败的吗

### ISSUE THREAD

**Issue by byouw** [huanghyw/jd_seckill#235]
2020-12-30 10:45:13,870 - 28260-MainThread - c:\Users\土豆\Desktop\jd_seckill-master\jd_spider_requests.py[line:208] - INFO: 已完成手机客户端确认
2020-12-30 10:45:14,106 - 28260-MainThread - c:\Users\土豆\Desktop\jd_seckill-master\jd_spider_requests.py[line:262] - INFO: 二维码登录成功
Traceback (most recent call last):
  File "c:/Users/土豆/Desktop/jd_seckill-master/main.py", line 26, in <module>
    jd_seckill.reserve()
  File "c:\Users\土豆\Desktop\jd_seckill-master\jd_spider_requests.py", line 309, in new_func
    self.login_by_qrcode()
  File "c:\Users\土豆\Desktop\jd_seckill-master\jd_spider_requests.py", line 299, in login_by_qrcode
    raise SKException("二维码登录失败！")
exception.SKException: 二维码登录失败！

**Comment by pigZ-27** [comment]
依赖包是否安装成功？
确认python版本 3.X?

**Comment by hailiangchen** [comment]
我的也是这个错误，Python 版本3.8.7 ；依赖包安装成功了。

**Comment by byouw** [comment]
python版本3.9.1。依赖第一次没安装成功，后面安装成功的。

**Comment by hailiangchen** [comment]
应该是账号开启了登录保护，我的关闭登录保护，就可以了。

**Comment by byouw** [comment]
> 应该是账号开启了登录保护，我的关闭登录保护，就可以了。

你好，这个登录保护是怎么回事，在哪里关的呐

**Comment by byouw** [comment]
> > 应该是账号开启了登录保护，我的关闭登录保护，就可以了。
> 
> 你好，这个登录保护是怎么回事，在哪里关的呐

你好，感谢，已经关闭了，登录成功了。

**Comment by byouw** [comment]
> 我的也是这个错误，Python 版本3.8.7 ；依赖包安装成功了。

你好，楼下有大哥回答的，关闭登录保护试试。我成功了。

**Comment by zhoushuuki** [comment]
请教，二维码登录在哪？我启动报错  def __init__(self, spider_session: SpiderSession):

**Comment by byouw** [comment]
> 请教，二维码登录在哪？我启动报错 def **init**(self, spider_session: SpiderSession):

二维码是启动成功之后才有的。
