### ISSUE TITLE
麻烦作者看看这是怎么回事呢？

### ISSUE THREAD

**Issue by lovefisher** [huanghyw/jd_seckill#24]
020-12-18 11:16:28,785 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:90] - INFO: 用户:哈哈哈大叔
2020-12-18 11:16:28,807 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:194] - INFO: 商品名称:【华硕RX6800-16G】华硕 ASUS AMD Radeon RX 6800台式机显卡 7nm AMD RDNA 2架构 16GB GDDR6游戏显卡【行情 报价 价格 评测】-京东
2020-12-18 11:16:28,808 - 75475-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:193] - INFO: 用户:哈哈哈大叔
2020-12-18 11:16:28,808 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:14] - INFO: 正在等待到达设定时间:2020-12-18 11:00:00.050000
2020-12-18 11:16:28,810 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:18] - INFO: 时间到达，开始执行……
2020-12-18 11:16:28,971 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:193] - INFO: 用户:哈哈哈大叔
2020-12-18 11:16:28,999 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:185] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100009495225&sn=852d38e3c0debb8ee9ea0210708915d4&from=pc
2020-12-18 11:16:28,999 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:197] - INFO: 访问商品的抢购连接...
2020-12-18 11:16:29,048 - 75479-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:193] - INFO: 用户:哈哈哈大叔
2020-12-18 11:16:29,087 - 75476-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:193] - INFO: 用户:哈哈哈大叔
2020-12-18 11:16:29,204 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:211] - INFO: 访问抢购订单结算页面...
2020-12-18 11:16:29,278 - 75475-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:194] - INFO: 商品名称:【华硕RX6800-16G】华硕 ASUS AMD Radeon RX 6800台式机显卡 7nm AMD RDNA 2架构 16GB GDDR6游戏显卡【行情 报价 价格 评测】-京东
2020-12-18 11:16:29,279 - 75475-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:14] - INFO: 正在等待到达设定时间:2020-12-18 11:00:00.050000
2020-12-18 11:16:29,280 - 75475-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:18] - INFO: 时间到达，开始执行……
2020-12-18 11:16:29,386 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:194] - INFO: 商品名称:【华硕RX6800-16G】华硕 ASUS AMD Radeon RX 6800台式机显卡 7nm AMD RDNA 2架构 16GB GDDR6游戏显卡【行情 报价 价格 评测】-京东
2020-12-18 11:16:29,387 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:14] - INFO: 正在等待到达设定时间:2020-12-18 11:00:00.050000
2020-12-18 11:16:29,388 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:18] - INFO: 时间到达，开始执行……
2020-12-18 11:16:29,455 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:247] - INFO: 生成提交抢购订单所需参数...
2020-12-18 11:16:29,455 - 75477-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:229] - INFO: 获取秒杀初始化信息...
2020-12-18 11:16:29,465 - 75475-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:185] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100009495225&sn=852d38e3c0debb8ee9ea0210708915d4&from=pc
2020-12-18 11:16:29,466 - 75475-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:197] - INFO: 访问商品的抢购连接...
2020-12-18 11:16:29,501 - 75479-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:194] - INFO: 商品名称:【华硕RX6800-16G】华硕 ASUS AMD Radeon RX 6800台式机显卡 7nm AMD RDNA 2架构 16GB GDDR6游戏显卡【行情 报价 价格 评测】-京东
2020-12-18 11:16:29,503 - 75479-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:14] - INFO: 正在等待到达设定时间:2020-12-18 11:00:00.050000
2020-12-18 11:16:29,504 - 75479-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:18] - INFO: 时间到达，开始执行……
2020-12-18 11:16:29,515 - 75476-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:194] - INFO: 商品名称:【华硕RX6800-16G】华硕 ASUS AMD Radeon RX 6800台式机显卡 7nm AMD RDNA 2架构 16GB GDDR6游戏显卡【行情 报价 价格 评测】-京东
2020-12-18 11:16:29,516 - 75476-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:14] - INFO: 正在等待到达设定时间:2020-12-18 11:00:00.050000
2020-12-18 11:16:29,518 - 75476-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/timer.py[line:18] - INFO: 时间到达，开始执行……
2020-12-18 11:16:29,579 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:185] - INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100009495225&sn=852d38e3c0debb8ee9ea0210708915d4&from=pc
2020-12-18 11:16:29,580 - 75478-MainThread - /Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py[line:197] - INFO: 访问商品的抢购连接...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 73, in __seckill
    if self.submit_seckill_order():
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 299, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data()
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 251, in _get_seckill_order_data
    default_address = init_info['addressList'][0]  # 默认地址dict
KeyError: 'addressList'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 28, in <module>
    jd_seckill.seckill_by_proc_pool()
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 49, in seckill_by_proc_pool
    pool.submit(self.seckill)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 615, in submit
    self._start_queue_management_thread()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 569, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 593, in _adjust_process_count
    p.start()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 34, in seckill
    self.__seckill()
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 76, in __seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (KeyError('addressList'),)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 73, in __seckill
    if self.submit_seckill_order():
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 299, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data()
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 251, in _get_seckill_order_data
    default_address = init_info['addressList'][0]  # 默认地址dict
KeyError: 'addressList'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 68, in emit
    if self.shouldRollover(record):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 184, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 28, in <module>
    jd_seckill.seckill_by_proc_pool()
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 49, in seckill_by_proc_pool
    pool.submit(self.seckill)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 615, in submit
    self._start_queue_management_thread()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 569, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 593, in _adjust_process_count
    p.start()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 34, in seckill
    self.__seckill()
  File "/Users/chenchuyuan/dev/LaravelCode/jd_seckill/jd_spider_requests.py", line 76, in __seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (KeyError('addressList'),)

**Comment by huanghyw** [comment]
确认一下cookie是否正常，最好是使用Chrome浏览器在订单结算页面获取

**Comment by huanghyw** [comment]
这些都没问题，就忽略该异常，这是接口没有正常返回json，而是返回了一个抢购失败的页面，导致信息获取失败

**Comment by lovefisher** [comment]
好的@huanghyw
