### ISSUE TITLE
运行main.py提示语法错误

### ISSUE THREAD

**Issue by heckerstone** [huanghyw/jd_seckill#248]
def __init__(self, spider_session: SpiderSession)这一句，提示信息如下：
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/mac/Downloads/jd_seckill-master/jd_spider_requests.py", line 106
    def __init__(self, spider_session: SpiderSession):
                                                          ^
SyntaxError: invalid syntax

**Comment by jianhoo727** [comment]
我也碰上了这个问题 :/
