### ISSUE TITLE
抢购中有报错

### ISSUE THREAD

**Issue by Mr-xin-Z** [huanghyw/jd_seckill#257]
2020-12-30 10:00:20,066 - 28777-MainThread - /media/jd_seckill/jd_spider_requests.py[line:497] - INFO: 获取秒杀初始化信息...
--- Logging error ---
Traceback (most recent call last):
  File "/media/jd_seckill/jd_spider_requests.py", line 358, in _seckill
    self.submit_seckill_order()
  File "/media/jd_seckill/jd_spider_requests.py", line 593, in submit_seckill_order
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 28, in <module>
    jd_seckill.seckill_by_proc_pool()
  File "/media/jd_seckill/jd_spider_requests.py", line 310, in new_func
    return func(self, *args, **kwargs)
  File "/media/jd_seckill/jd_spider_requests.py", line 335, in seckill_by_proc_pool
    pool.submit(self.seckill)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 466, in submit
    self._start_queue_management_thread()
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 446, in _adjust_process_count
    p.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/media/jd_seckill/jd_spider_requests.py", line 310, in new_func
    return func(self, *args, **kwargs)
  File "/media/jd_seckill/jd_spider_requests.py", line 325, in seckill
    self._seckill()
  File "/media/jd_seckill/jd_spider_requests.py", line 360, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (TooManyRedirects('Exceeded 30 redirects.',),)
--- Logging error ---
Traceback (most recent call last):
  File "/media/jd_seckill/jd_spider_requests.py", line 358, in _seckill
    self.submit_seckill_order()
  File "/media/jd_seckill/jd_spider_requests.py", line 593, in submit_seckill_order
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 28, in <module>
    jd_seckill.seckill_by_proc_pool()
  File "/media/jd_seckill/jd_spider_requests.py", line 310, in new_func
    return func(self, *args, **kwargs)
  File "/media/jd_seckill/jd_spider_requests.py", line 335, in seckill_by_proc_pool
    pool.submit(self.seckill)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 466, in submit
    self._start_queue_management_thread()
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 446, in _adjust_process_count
    p.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/media/jd_seckill/jd_spider_requests.py", line 310, in new_func
    return func(self, *args, **kwargs)
  File "/media/jd_seckill/jd_spider_requests.py", line 325, in seckill
    self._seckill()
  File "/media/jd_seckill/jd_spider_requests.py", line 360, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'

**Comment by RoyalLiang** [comment]
+1

**Comment by badouyuren** [comment]
+1
