### ISSUE TITLE
python main.py无法正常启动

### ISSUE THREAD

**Issue by fxxph** [huanghyw/jd_seckill#284]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_spider_requests import JdSeckill
  File "/Users/xxxxxx/Downloads/jd_seckill-master/jd_spider_requests.py", line 105
    def __init__(self, spider_session: SpiderSession):
                                     ^
SyntaxError: invalid syntax

你们有遇到吗。。

**Comment by supermqB** [comment]
python3

**Comment by fxxph** [comment]
> python3

嗯嗯，升级后可以运行了～👍
