### ISSUE TITLE
今天运行的时候，发生了这个错误

### ISSUE THREAD

**Issue by oycl** [huanghyw/jd_seckill#309]
功能列表：
 1.预约商品
 2.秒杀抢购商品

请选择:2
Process SpawnProcess-1:
Traceback (most recent call last):
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Process SpawnProcess-4:
Process SpawnProcess-2:
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\odoo_dev\python3.7.2\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
Traceback (most recent call last):
OSError: [WinError 6] 句柄无效。
Process SpawnProcess-5:
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\odoo_dev\python3.7.2\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
Traceback (most recent call last):
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\odoo_dev\python3.7.2\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
Process SpawnProcess-3:
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
  File "D:\odoo_dev\python3.7.2\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
OSError: [WinError 6] 句柄无效。
OSError: [WinError 6] 句柄无效。
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
Traceback (most recent call last):
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
OSError: [WinError 6] 句柄无效。
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\odoo_dev\python3.7.2\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "D:\odoo_dev\python3.7.2\lib\multiprocessing\synchronize.py", line 98, in __exit__
    return self._semlock.__exit__(*args)
OSError: [WinError 6] 句柄无效。

**Comment by Vincentjianpeng** [comment]
同样，昨天还正常，可能是更新了代码

**Comment by oycl** [comment]
昨晚的不正常，今天重新拉的代码也是这个错误。。
