### ISSUE TITLE
扫码后一直提示二维码信息校验失败，有遇到这个情况的吗

### ISSUE THREAD

**Issue by zenpe** [huanghyw/jd_seckill#311]
2020-12-30 11:17:15,819 - 32436-MainThread - /Users/pzeng/work/jd_seckill/jd_spider_requests.py[line:312] - INFO: reserve 需登陆后调用，开始扫码登陆
2020-12-30 11:17:26,854 - 32436-MainThread - /Users/pzeng/work/jd_seckill/jd_spider_requests.py[line:178] - INFO: 二维码获取成功，请打开京东APP扫描
2020-12-30 11:17:29,362 - 32436-MainThread - /Users/pzeng/work/jd_seckill/jd_spider_requests.py[line:209] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2020-12-30 11:17:34,155 - 32436-MainThread - /Users/pzeng/work/jd_seckill/jd_spider_requests.py[line:212] - INFO: 已完成手机客户端确认
2020-12-30 11:17:36,764 - 32436-MainThread - /Users/pzeng/work/jd_seckill/jd_spider_requests.py[line:235] - INFO: {'returnCode': 80}
Traceback (most recent call last):
  File "/Users/pzeng/work/jd_seckill/main.py", line 26, in <module>
    jd_seckill.reserve()
  File "/Users/pzeng/work/jd_seckill/jd_spider_requests.py", line 313, in new_func
    self.login_by_qrcode()
  File "/Users/pzeng/work/jd_seckill/jd_spider_requests.py", line 297, in login_by_qrcode
    self.qrlogin.login_by_qrcode()
  File "/Users/pzeng/work/jd_seckill/jd_spider_requests.py", line 262, in login_by_qrcode
    raise SKException('二维码信息校验失败')
exception.SKException: 二维码信息校验失败

**Comment by xcloudss** [comment]
有啊，请问如何解决的

**Comment by zenpe** [comment]
> 有啊，请问如何解决的

测试了下，是由于挂了系统代理导致的，关掉代理就ok了
