### ISSUE TITLE
BUG：抢购异常

### ISSUE THREAD

**Issue by ZRT-1998** [huanghyw/jd_seckill#339]
2020-12-30 10:05:09,267 - 27224-MainThread - G:\jd_spider_requests.py[line:580] - INFO: 提交抢购订单...
2020-12-30 10:05:09,441 - 27224-MainThread - G:\jd_spider_requests.py[line:616] - INFO: 抢购失败，返回信息:{'errorMessage': '很遗憾没有抢到，再接再厉哦。', 'orderId': 0, 'resultCode': 90016, 'skuId': 0, 'success': False}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'enable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:jd_spider_requests.py", line 357, in _seckill
    self.submit_seckill_order()
  File "G:jd_spider_requests.py", line 617, in submit_seckill_order
    if global_config.getRaw('messenger', 'enable') == 'true':
  File "G:config.py", line 19, in getRaw
    return self._configRaw.get(section, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'enable' in section: 'messenger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1079, in emit
    msg = self.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 923, in format
    return fmt.format(record)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 659, in format
    record.message = record.getMessage()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "G:\jd_spider_requests.py", line 310, in new_func
    return func(self, *args, **kwargs)
  File "G:\jd_spider_requests.py", line 325, in seckill
    self._seckill()
  File "G:\python\Py project\Jdms1\5\jd_spider_requests.py", line 359, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'

**Comment by huanghyw** [comment]
检查下配置文件关于messenger的配置是否正确

**Comment by ZRT-1998** [comment]
没有调用messenger

**Comment by ZRT-1998** [comment]
我注释掉了

**Comment by huanghyw** [comment]
就算不用配置也需要存在，只不过禁用就行

**Comment by huanghyw** [comment]
不能直接注释

**Comment by ZRT-1998** [comment]
他好像没有影响我运行

**Comment by huanghyw** [comment]
这个server酱在每次流程的末尾，所以没有影响到

**Comment by ZRT-1998** [comment]
没有比较好的推送消息的工具吗，sever酱和邮箱都顶不住循环的接收消息

**Comment by ZRT-1998** [comment]
我今天开了3个main，一个都没有，是被盾了吗？

**Comment by huanghyw** [comment]
自己微调一下，只保留成功发送 :)
