### ISSUE TITLE
报了个错

### ISSUE THREAD

**Issue by wzphood** [huanghyw/jd_seckill#45]
msg = msg % self.args
TypeError: not all arguments converted during string formatting
是配置出错了吗

**Comment by huanghyw** [comment]
这个异常信息太少了，多提供一点日志

**Comment by wzphood** [comment]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 357, in _seckill
    self.submit_seckill_order()
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 566, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data()
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 516, in _get_seckill_order_data
    self.seckill_init_info[self.sku_id] = self._get_seckill_init_info()
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 508, in _get_seckill_init_info
    return parse_json(resp.text)
  File "C:\Users\admin\PycharmProjects\jd_seckill\util.py", line 66, in parse_json
    return json.loads(s[begin:end])
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1079, in emit
    msg = self.format(record)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 923, in format
    return fmt.format(record)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 659, in format
    record.message = record.getMessage()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 310, in new_func
    return func(self, *args, **kwargs)
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 325, in seckill
    self._seckill()
  File "C:\Users\admin\PycharmProjects\jd_seckill\jd_spider_requests.py", line 359, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (JSONDecodeError('Expecting value: line 1 column 1 (char 0)'),)

**Comment by huanghyw** [comment]
这个异常忽略就行，接口没有返回json，导致无法解析。
更新下代码，这种场景已经处理了，会直接提示失败。

**Comment by wzphood** [comment]
OK
话说大佬有考虑做监控预售的功能吗，现在有个不定时放货的预售商品，不知道怎么抢

**Comment by DLwyp** [comment]
大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题

**Comment by huanghyw** [comment]
> OK
> 话说大佬有考虑做监控预售的功能吗，现在有个不定时放货的预售商品，不知道怎么抢

这个先不考虑了，目前主要关注茅台抢购的流程

**Comment by huanghyw** [comment]
> 大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题

没有交流群。
时间问题一直存在，等等，后续版本会有优化。

**Comment by DLwyp** [comment]
> > OK
> > 话说大佬有考虑做监控预售的功能吗，现在有个不定时放货的预售商品，不知道怎么抢
> 
> 这个先不考虑了，目前主要关注茅台抢购的流程

大佬看下我上一层的问题

**Comment by DLwyp** [comment]
> > 大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题
> 
> 没有交流群。
> 时间问题一直存在，等等，后续版本会有优化。

我之前想做同步jd服务器时间，实时修改本地时间，但是windows的实时修改时间比较复杂。你抢购时间设置的是提前500ms吗？

**Comment by huanghyw** [comment]
> > > 大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题
> > 
> > 
> > 没有交流群。
> > 时间问题一直存在，等等，后续版本会有优化。
> 
> 我之前想做同步jd服务器时间，实时修改本地时间，但是windows的实时修改时间比较复杂。你抢购时间设置的是提前500ms吗？

对，我一般提前500毫秒

**Comment by DLwyp** [comment]
> > > > 大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题
> > > 
> > > 
> > > 没有交流群。
> > > 时间问题一直存在，等等，后续版本会有优化。
> > 
> > 
> > 我之前想做同步jd服务器时间，实时修改本地时间，但是windows的实时修改时间比较复杂。你抢购时间设置的是提前500ms吗？
> 
> 对，我一般提前500毫秒

好的，谢谢大佬

**Comment by huanghyw** [comment]
> > > 大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题
> > 
> > 
> > 没有交流群。
> > 时间问题一直存在，等等，后续版本会有优化。
> 
> 我之前想做同步jd服务器时间，实时修改本地时间，但是windows的实时修改时间比较复杂。你抢购时间设置的是提前500ms吗？

同步京东时间上线了，您更新下代码

**Comment by DLwyp** [comment]
> > > > 大佬有没有交流群啊，我之前用windows测试，遇到了时间同步的问题
> > > 
> > > 
> > > 没有交流群。
> > > 时间问题一直存在，等等，后续版本会有优化。
> > 
> > 
> > 我之前想做同步jd服务器时间，实时修改本地时间，但是windows的实时修改时间比较复杂。你抢购时间设置的是提前500ms吗？
> 
> 同步京东时间上线了，您更新下代码

大佬神速啊，tql
