### ISSUE TITLE
优化了今天也没抢到，是不是限制区域了。进群讨论（短时间有效）

### ISSUE THREAD

**Issue by 8090shuo** [huanghyw/jd_seckill#463]
> 加WX：keshao87
> 暗号：京东
> 我拉群了...
> 验证通过才可以进

上面号如果频繁了，可以扫下面二维码通过
加一个就行了！
暗号：京东
同样需要验证通过才可以进
![微信图片_20210106113401](https://user-images.githubusercontent.com/58967572/103726275-76a41e80-5013-11eb-95b6-b8ae64cad534.jpg)

**Comment by leishi-1** [comment]
扫码登录失败， 返回code 80  有人跟我一样的么？

2021-01-08 10:34:30,925 - 8-MainThread - /app/jd_seckill/jd_spider_requests.py[line:241] - INFO: {'returnCode': 80}
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    jd_seckill.reserve()
  File "/app/jd_seckill/jd_spider_requests.py", line 319, in new_func
    self.login_by_qrcode()
  File "/app/jd_seckill/jd_spider_requests.py", line 303, in login_by_qrcode
    self.qrlogin.login_by_qrcode()
  File "/app/jd_seckill/jd_spider_requests.py", line 268, in login_by_qrcode
    raise SKException('二维码信息校验失败')
jd_seckill.exception.SKException: 二维码信息校验失败

**Comment by zpp0318** [comment]
> > 加WX：keshao87
> > 暗号：京东
> > 我拉群了...
> > 验证通过才可以进
> 
> 上面号如果频繁了，可以扫下面二维码通过
> 加一个就行了！
> 暗号：京东
> 同样需要验证通过才可以进
> ![微信图片_20210106113401](https://user-images.githubusercontent.com/58967572/103726275-76a41e80-5013-11eb-95b6-b8ae64cad534.jpg)
你这个图片我怎么加载不出来 打不开
