### ISSUE TITLE
扫码显示二维码效验信息失败

### ISSUE THREAD

**Issue by Rivendell-PandaTv** [huanghyw/jd_seckill#62]
RT

**Comment by huanghyw** [comment]
操作系统是什么？

**Comment by huanghyw** [comment]
还有日志提供下

**Comment by Rivendell-PandaTv** [comment]
windows7 旗舰版，python3.7，日志请稍等。



rivendell@vip.qq.com
 
发件人： 红头土豆
发送时间： 2020-12-24 15:20
收件人： huanghyw/jd_seckill
抄送： Rivendell-PandaTv; Author
主题： Re: [huanghyw/jd_seckill] 扫码显示二维码效验信息失败 (#62)
操作系统是什么？

**Comment by Rivendell-PandaTv** [comment]
2020-12-24 15:42:29,510 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:308] - INFO: reserve 需登陆后调用，开始扫码登陆
2020-12-24 15:42:38,395 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:177] - INFO: 二维码获取成功，请打开京东APP扫描
2020-12-24 15:42:42,252 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:205] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2020-12-24 15:42:46,160 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:205] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2020-12-24 15:42:49,986 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:205] - INFO: Code: 201, Message: 二维码未扫描，请扫描二维码
2020-12-24 15:42:53,543 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:208] - INFO: 已完成手机客户端确认
2020-12-24 15:42:55,309 - 10712-MainThread - C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py[line:231] - INFO: {'returnCode': 80}
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\main.py", line 26, in <module>
    jd_seckill.reserve()
  File "C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py", line 309, in new_func
    self.login_by_qrcode()
  File "C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py", line 293, in login_by_qrcode
    self.qrlogin.login_by_qrcode()
  File "C:\Users\Administrator\Downloads\Compressed\jd_seckill-master\jd_spider_requests.py", line 258, in login_by_qrcode
    raise SKException('二维码信息校验失败')
exception.SKException: 二维码信息校验失败

**Comment by huanghyw** [comment]
换一个图片查看器重新扫码试试？

**Comment by Rivendell-PandaTv** [comment]
换了蜂蜜，还是失败。哈哈。

**Comment by huanghyw** [comment]
手机京东登出，删除项目里面的cookie文件，然后重新登录手机京东，重新扫码试试

**Comment by huanghyw** [comment]
代码更新到最新版本
